app:
  Name: TodoApp
  Port:  :8080

database: 
  Addr: 127.0.0.1:3306
  User: root
  Password: [your_password_here]
  Name: todoapp
  MaxIdleConns: 10
  MaxOpenConns: 100
  ConnMaxLifetime: 1

CORSConfig:
  AllowOrigins: http://localhost:3000
